---
abstract: 'decode and encode NetFlow/IPFIX datagrams.'
author:
  - 'Atsushi KOBAYASHI <akoba@nttv6.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Flow
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.002
